# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/bt_atoms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-frameworks/proto_logging/stats/bt_atoms.proto\x12\x11\x61ndroid.os.statsd\"r\n\x04\x41tom\x12`\n\"bluetooth_connection_state_changed\x18\x44 \x01(\x0b\x32\x32.android.os.statsd.BluetoothConnectionStateChangedH\x00\x42\x08\n\x06pushed\"\xe7\x01\n\x1f\x42luetoothConnectionStateChanged\x12\x35\n\x05state\x18\x01 \x01(\x0e\x32&.android.os.statsd.ConnectionStateEnum\x12\x19\n\robfuscated_id\x18\x02 \x01(\x05\x42\x02\x18\x01\x12\x12\n\nbt_profile\x18\x03 \x01(\x05\x12\x19\n\x11new_obfuscated_id\x18\x04 \x01(\x0c\x12\x11\n\tmetric_id\x18\x05 \x01(\x05\x12\x15\n\rsession_index\x18\x06 \x01(\x05\x12\x19\n\x11\x63onnection_reason\x18\x07 \x01(\x05*\x9d\x01\n\x13\x43onnectionStateEnum\x12!\n\x1d\x43ONNECTION_STATE_DISCONNECTED\x10\x00\x12\x1f\n\x1b\x43ONNECTION_STATE_CONNECTING\x10\x01\x12\x1e\n\x1a\x43ONNECTION_STATE_CONNECTED\x10\x02\x12\"\n\x1e\x43ONNECTION_STATE_DISCONNECTING\x10\x03\x42\x1e\n\x0e\x63om.android.osB\nAtomsProtoH\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frameworks.proto_logging.stats.bt_atoms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.android.osB\nAtomsProtoH\002'
  _BLUETOOTHCONNECTIONSTATECHANGED.fields_by_name['obfuscated_id']._options = None
  _BLUETOOTHCONNECTIONSTATECHANGED.fields_by_name['obfuscated_id']._serialized_options = b'\030\001'
  _CONNECTIONSTATEENUM._serialized_start=419
  _CONNECTIONSTATEENUM._serialized_end=576
  _ATOM._serialized_start=68
  _ATOM._serialized_end=182
  _BLUETOOTHCONNECTIONSTATECHANGED._serialized_start=185
  _BLUETOOTHCONNECTIONSTATECHANGED._serialized_end=416
# @@protoc_insertion_point(module_scope)
